version: 1

formatters:
   simple:
      format: "%(asctime)s - [%(levelname)s] - name)s - (%(filename)s).%(funcName)s(%(lineno)d) - %(message)s"

handlers:
   common:
      class: logging.handlers.RotatingFileHandler
      filename: vtc-bot.log
      maxBytes: 33554432
      backupCount: 10
      encoding: utf8
      formatter: simple

loggers:
   discord:
      level: DEBUG
      handlers: [common,]
   discord.http:
      level: INFO
