name: Код дискор бота чееееееееееееееееееееееееееееек

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry update
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      # - name: Run tests
      #   run: pytest