name: Код дискор бота чееееееееееееееееееееееееееееек

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        env:
          # POSTGRES_HOST: postgres
          # POSTGRES_PORT: 5432
          POSTGRES_USER: "${{ secrets.POSTGRES_USER}}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD}}"
          # POSTGRES_DB_SEC: "${{ secrets.POSTGRES_DB}}"
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry update
      # - name: Run flake8
      #   run: poetry run flake8
      # - name: Run mypy
      #   run: poetry run mypy
      - name: Run tests
        run: |
          echo $POSTGRES_DB_SEC
          poetry run pytest