name: Код дискор бота чееееееееееееееееееееееееееееек

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
<<<<<<< HEAD
<<<<<<< HEAD
=======
        env:
          # POSTGRES_HOST: postgres
          # POSTGRES_PORT: 5432
          POSTGRES_USER: "${{ secrets.POSTGRES_USER}}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD}}"
          # POSTGRES_DB_SEC: "${{ secrets.POSTGRES_DB}}"
>>>>>>> d9dbfa8 (Интегрирована сотая попытка запустить тесты в workflow.)
=======
>>>>>>> 6732bfe (Добавлена попытка получить доступ к БД.)
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry update
      - name: Run flake8
<<<<<<< HEAD
        run: poetry run flake8 --config ./config.flake8
=======
        run: poetry run flake8
>>>>>>> 6732bfe (Добавлена попытка получить доступ к БД.)
      - name: Run mypy
        run: poetry run mypy
      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
<<<<<<< HEAD
          poetry run pytest
=======
          poetry run pytest
>>>>>>> 6732bfe (Добавлена попытка получить доступ к БД.)
